### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\laZzzy-main\\output'

### ISSUE THREAD

**Issue by matt-culbert** [capt-meelo/laZzzy#1]
Small QoL thing, adding the output folder to the Github structure would make launching the first time easier. As it is now, you have to add the folder after downloading.

**Comment by capt-meelo** [comment]
This function will create the necessary folder.
```python
def clean_output():
    output_dir = f"{os.getcwd()}\output"
    shutil.rmtree(output_dir)
    os.makedirs(output_dir)
```

**Comment by matt-culbert** [comment]
It looks like it errors on shutil.rmtree(output_dir) returning that "FileNotFoundError: [WinError 3] The system cannot find the path specified" because the folder does not exist on first run. Encasing the shutil.rmtree(output_dir) in a try except statement fixes this.

```python
def clean_output():
    output_dir = f"{os.getcwd()}\output"
    try:
        shutil.rmtree(output_dir)
    except:
        pass
    os.makedirs(output_dir)
```

**Comment by capt-meelo** [comment]
You're right on that. I missed that check. Thanks for letting me know. Do you want to make the PR for this?

**Comment by matt-culbert** [comment]
Sure thing, I appreciate it! Just opened it, let me know if there's any issues

**Comment by capt-meelo** [comment]
Thanks!
